In [4]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [6]:
66/5

13.2

In [7]:
66//5

13

In [12]:
s = r'this has\no\special\characters'
s

'this has\\no\\special\\characters'

In [14]:
template = '{0:.2f} {1:s} are worth US${2:d}'
# template.format(4.5560,1, 'Argentine Pesos')


In [18]:
for i in range(10,20,2):
    print(i)

10
12
14
16
18


In [20]:
tup=4,5,6
tup

(4, 5, 6)

In [21]:
tuple("sexy")

('s', 'e', 'x', 'y')

In [22]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
type(seq)

list

In [54]:
seq = [0,1,2,3,4,5,6,7]

In [55]:
seq[-4:]

[4, 5, 6, 7]

In [56]:
seq[::-1]

[7, 6, 5, 4, 3, 2, 1, 0]

In [62]:
seq[:-8:-1]

[7, 6, 5, 4, 3, 2, 1]

In [67]:
seq[:-8:-2]

[7, 5, 3, 1]

In [68]:
seq[:-8]

[]

In [71]:
seq[:-4:-1]

[7, 6, 5]

In [72]:
seq[:-4]

[0, 1, 2, 3]

In [75]:
seq[-1:-7:-1]

[7, 6, 5, 4, 3, 2]

In [76]:
some_list = ['foo', 'bar', 'baz']

In [86]:
map={}
for i,v in enumerate(some_list):
    map[v]=len(v)
map    

{'foo': 3, 'bar': 3, 'baz': 3}

In [87]:
pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),
       ....:             ('Schilling', 'Curt')]

In [90]:
for (a,b) in pitchers:
    print(a," and ",b)

Nolan  and  Ryan
Roger  and  Clemens
Schilling  and  Curt


In [99]:
for i in (pitchers): 
    print(i)

('Nolan', 'Ryan')
('Roger', 'Clemens')
('Schilling', 'Curt')


In [114]:
for i in zip(pitchers,"sexy"):
    print(i[0],"->",i[1])

('Nolan', 'Ryan') -> s
('Roger', 'Clemens') -> e
('Schilling', 'Curt') -> x


In [115]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
       .....:             ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]


In [121]:
result=[i for names in all_data for i in names if(i.count('e')>1)]
result

['Steven']

In [122]:
numbers = [3,5,45,97,32,22,10,19,39,43]

In [144]:
odd=[i*i for i in numbers if(i%2!=0)]
odd

[9, 25, 2025, 9409, 361, 1521, 1849]

In [130]:
original_list = [2,3.75,.04,59.354,6,7.7777,8,9]
int_=[i for i in original_list if(type(i)==int)]
int_

[2, 6, 8, 9]

In [135]:
# Find all of the numbers from 1-1000 that have a 3 in them
ans=[i for i in range(951,1000) if( str(i).count('3')>0)]
ans

[953, 963, 973, 983, 993]

In [137]:
#Count the number of spaces in a string
s="i am ja tin , the man who will become the Millionaire Pirate..."
s.count(" ")

12

In [140]:
# Find the common numbers in two lists (without using a tuple or set) list_a = 1, 2, 3, 4, list_b = 2, 3, 4, 5
list_a = 1, 2, 3, 4
list_b = 2, 3, 4, 5

cmn=[i for i in list_a if i in list_b]
cmn

[2, 3, 4]

In [150]:
some_dict = {'a': 1, 'b': 2, 'c': 3}
for i in some_dict:
    print(i)

a
b
c


In [156]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [169]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
two=numeric_strings.astype(float)
two

array([ 1.25, -9.6 , 42.  ])

In [170]:
two.astype(int)

array([ 1, -9, 42])

In [190]:
arr = np.arange(10)
l=list(range(10))


In [191]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [192]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
x=l[5:8]
x[1]=100000
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [196]:
y=arr[5:8]
y[1]=100000
arr

array([     0,      1,      2,      3,      4,      5, 100000,      7,
            8,      9])

In [225]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe','Bob'])
data = np.random.randn(7, 4)

In [226]:
data

array([[ 0.46563573, -1.97254101, -0.29965437,  1.07351282],
       [ 0.18817101, -0.179827  , -1.65558635,  0.09282285],
       [-0.6653372 , -0.22047241, -1.34823466,  0.42547183],
       [ 0.50014911, -0.66473555, -0.16297777, -1.24865796],
       [ 0.05891334,  1.48790362,  0.13571562,  1.7584087 ],
       [-0.58417307,  0.02871745,  1.65783393,  0.13131513],
       [ 0.4664894 ,  2.06208156,  1.55222692,  0.84807996]])

In [227]:
names=='Bob'

array([ True, False, False,  True, False, False,  True])

In [228]:
data[names=='Bob']

array([[ 0.46563573, -1.97254101, -0.29965437,  1.07351282],
       [ 0.50014911, -0.66473555, -0.16297777, -1.24865796],
       [ 0.4664894 ,  2.06208156,  1.55222692,  0.84807996]])

In [229]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [231]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [241]:
arr[[1,5,7,2]][:,[3,0,1,2]]

array([[ 7,  4,  5,  6],
       [23, 20, 21, 22],
       [31, 28, 29, 30],
       [11,  8,  9, 10]])

In [250]:
arr[:3:-1,:]

array([[28, 29, 30, 31],
       [24, 25, 26, 27],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

In [251]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [253]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [255]:
obj[1]

1.0

In [259]:
obj.iloc[::-1]

d    3.0
c    2.0
b    1.0
a    0.0
dtype: float64